// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: datasource.proto

package datasourcev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Type              string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Credentials       *structpb.Struct       `protobuf:"bytes,2,opt,name=credentials,proto3" json:"credentials,omitempty"`
	ResourceIds       []string               `protobuf:"bytes,3,rep,name=resource_ids,json=resourceIds,proto3" json:"resource_ids,omitempty"`
	Settings          *structpb.Struct       `protobuf:"bytes,4,opt,name=settings,proto3" json:"settings,omitempty"`
	MultimodalEnabled bool                   `protobuf:"varint,5,opt,name=multimodal_enabled,json=multimodalEnabled,proto3" json:"multimodal_enabled,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_datasource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Config) GetCredentials() *structpb.Struct {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *Config) GetResourceIds() []string {
	if x != nil {
		return x.ResourceIds
	}
	return nil
}

func (x *Config) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *Config) GetMultimodalEnabled() bool {
	if x != nil {
		return x.MultimodalEnabled
	}
	return false
}

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	ModifiedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	ParentId      string                 `protobuf:"bytes,7,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	HasChildren   bool                   `protobuf:"varint,8,opt,name=has_children,json=hasChildren,proto3" json:"has_children,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_datasource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{1}
}

func (x *Resource) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Resource) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Resource) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Resource) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

func (x *Resource) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Resource) GetHasChildren() bool {
	if x != nil {
		return x.HasChildren
	}
	return false
}

func (x *Resource) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Cursor struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LastSyncTime    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=last_sync_time,json=lastSyncTime,proto3" json:"last_sync_time,omitempty"`
	ConnectorCursor *structpb.Struct       `protobuf:"bytes,2,opt,name=connector_cursor,json=connectorCursor,proto3" json:"connector_cursor,omitempty"`
	LastSchemaHash  string                 `protobuf:"bytes,3,opt,name=last_schema_hash,json=lastSchemaHash,proto3" json:"last_schema_hash,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Cursor) Reset() {
	*x = Cursor{}
	mi := &file_datasource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cursor) ProtoMessage() {}

func (x *Cursor) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cursor.ProtoReflect.Descriptor instead.
func (*Cursor) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{2}
}

func (x *Cursor) GetLastSyncTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSyncTime
	}
	return nil
}

func (x *Cursor) GetConnectorCursor() *structpb.Struct {
	if x != nil {
		return x.ConnectorCursor
	}
	return nil
}

func (x *Cursor) GetLastSchemaHash() string {
	if x != nil {
		return x.LastSchemaHash
	}
	return ""
}

type FetchedItem struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExternalId       string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content          []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ContentType      string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	FileName         string                 `protobuf:"bytes,5,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Url              string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Metadata         map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IsDeleted        bool                   `protobuf:"varint,9,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	SourceResourceId string                 `protobuf:"bytes,10,opt,name=source_resource_id,json=sourceResourceId,proto3" json:"source_resource_id,omitempty"`
	ReplacesSubtree  bool                   `protobuf:"varint,11,opt,name=replaces_subtree,json=replacesSubtree,proto3" json:"replaces_subtree,omitempty"`
	SubtreeKeep      []string               `protobuf:"bytes,12,rep,name=subtree_keep,json=subtreeKeep,proto3" json:"subtree_keep,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FetchedItem) Reset() {
	*x = FetchedItem{}
	mi := &file_datasource_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchedItem) ProtoMessage() {}

func (x *FetchedItem) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchedItem.ProtoReflect.Descriptor instead.
func (*FetchedItem) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{3}
}

func (x *FetchedItem) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *FetchedItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FetchedItem) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FetchedItem) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *FetchedItem) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FetchedItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FetchedItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *FetchedItem) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *FetchedItem) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *FetchedItem) GetSourceResourceId() string {
	if x != nil {
		return x.SourceResourceId
	}
	return ""
}

func (x *FetchedItem) GetReplacesSubtree() bool {
	if x != nil {
		return x.ReplacesSubtree
	}
	return false
}

func (x *FetchedItem) GetSubtreeKeep() []string {
	if x != nil {
		return x.SubtreeKeep
	}
	return nil
}

type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_datasource_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{4}
}

type DescribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Capabilities  []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Contracts     []string               `protobuf:"bytes,4,rep,name=contracts,proto3" json:"contracts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_datasource_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{5}
}

func (x *DescribeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DescribeResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DescribeResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *DescribeResponse) GetContracts() []string {
	if x != nil {
		return x.Contracts
	}
	return nil
}

type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *Config                `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_datasource_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateRequest) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_datasource_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ValidateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *Config                `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	ParentId      string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesRequest) Reset() {
	*x = ListResourcesRequest{}
	mi := &file_datasource_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesRequest) ProtoMessage() {}

func (x *ListResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesRequest.ProtoReflect.Descriptor instead.
func (*ListResourcesRequest) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{8}
}

func (x *ListResourcesRequest) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ListResourcesRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type ListResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*Resource            `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesResponse) Reset() {
	*x = ListResourcesResponse{}
	mi := &file_datasource_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesResponse) ProtoMessage() {}

func (x *ListResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesResponse.ProtoReflect.Descriptor instead.
func (*ListResourcesResponse) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{9}
}

func (x *ListResourcesResponse) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

type ResolveAncestorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *Config                `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	ResourceIds   []string               `protobuf:"bytes,2,rep,name=resource_ids,json=resourceIds,proto3" json:"resource_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveAncestorsRequest) Reset() {
	*x = ResolveAncestorsRequest{}
	mi := &file_datasource_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAncestorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAncestorsRequest) ProtoMessage() {}

func (x *ResolveAncestorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAncestorsRequest.ProtoReflect.Descriptor instead.
func (*ResolveAncestorsRequest) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{10}
}

func (x *ResolveAncestorsRequest) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ResolveAncestorsRequest) GetResourceIds() []string {
	if x != nil {
		return x.ResourceIds
	}
	return nil
}

type ResolveAncestorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AncestorIds   []string               `protobuf:"bytes,1,rep,name=ancestor_ids,json=ancestorIds,proto3" json:"ancestor_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveAncestorsResponse) Reset() {
	*x = ResolveAncestorsResponse{}
	mi := &file_datasource_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAncestorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAncestorsResponse) ProtoMessage() {}

func (x *ResolveAncestorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAncestorsResponse.ProtoReflect.Descriptor instead.
func (*ResolveAncestorsResponse) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{11}
}

func (x *ResolveAncestorsResponse) GetAncestorIds() []string {
	if x != nil {
		return x.AncestorIds
	}
	return nil
}

type FetchStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *Config                `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	ResourceIds   []string               `protobuf:"bytes,2,rep,name=resource_ids,json=resourceIds,proto3" json:"resource_ids,omitempty"`
	Cursor        *Cursor                `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchStreamRequest) Reset() {
	*x = FetchStreamRequest{}
	mi := &file_datasource_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchStreamRequest) ProtoMessage() {}

func (x *FetchStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchStreamRequest.ProtoReflect.Descriptor instead.
func (*FetchStreamRequest) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{12}
}

func (x *FetchStreamRequest) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *FetchStreamRequest) GetResourceIds() []string {
	if x != nil {
		return x.ResourceIds
	}
	return nil
}

func (x *FetchStreamRequest) GetCursor() *Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

type FetchStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*FetchStreamResponse_Item
	//	*FetchStreamResponse_Checkpoint
	//	*FetchStreamResponse_FinalCursor
	Payload       isFetchStreamResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchStreamResponse) Reset() {
	*x = FetchStreamResponse{}
	mi := &file_datasource_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchStreamResponse) ProtoMessage() {}

func (x *FetchStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchStreamResponse.ProtoReflect.Descriptor instead.
func (*FetchStreamResponse) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{13}
}

func (x *FetchStreamResponse) GetPayload() isFetchStreamResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *FetchStreamResponse) GetItem() *FetchedItem {
	if x != nil {
		if x, ok := x.Payload.(*FetchStreamResponse_Item); ok {
			return x.Item
		}
	}
	return nil
}

func (x *FetchStreamResponse) GetCheckpoint() *Cursor {
	if x != nil {
		if x, ok := x.Payload.(*FetchStreamResponse_Checkpoint); ok {
			return x.Checkpoint
		}
	}
	return nil
}

func (x *FetchStreamResponse) GetFinalCursor() *Cursor {
	if x != nil {
		if x, ok := x.Payload.(*FetchStreamResponse_FinalCursor); ok {
			return x.FinalCursor
		}
	}
	return nil
}

type isFetchStreamResponse_Payload interface {
	isFetchStreamResponse_Payload()
}

type FetchStreamResponse_Item struct {
	Item *FetchedItem `protobuf:"bytes,1,opt,name=item,proto3,oneof"`
}

type FetchStreamResponse_Checkpoint struct {
	Checkpoint *Cursor `protobuf:"bytes,2,opt,name=checkpoint,proto3,oneof"`
}

type FetchStreamResponse_FinalCursor struct {
	FinalCursor *Cursor `protobuf:"bytes,3,opt,name=final_cursor,json=finalCursor,proto3,oneof"`
}

func (*FetchStreamResponse_Item) isFetchStreamResponse_Payload() {}

func (*FetchStreamResponse_Checkpoint) isFetchStreamResponse_Payload() {}

func (*FetchStreamResponse_FinalCursor) isFetchStreamResponse_Payload() {}

var File_datasource_proto protoreflect.FileDescriptor

const file_datasource_proto_rawDesc = "" +
	"\n" +
	"\x10datasource.proto\x12\x1cweknora.plugin.datasource.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xde\x01\n" +
	"\x06Config\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x129\n" +
	"\vcredentials\x18\x02 \x01(\v2\x17.google.protobuf.StructR\vcredentials\x12!\n" +
	"\fresource_ids\x18\x03 \x03(\tR\vresourceIds\x123\n" +
	"\bsettings\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bsettings\x12-\n" +
	"\x12multimodal_enabled\x18\x05 \x01(\bR\x11multimodalEnabled\"\x93\x03\n" +
	"\bResource\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12;\n" +
	"\vmodified_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt\x12\x1b\n" +
	"\tparent_id\x18\a \x01(\tR\bparentId\x12!\n" +
	"\fhas_children\x18\b \x01(\bR\vhasChildren\x12P\n" +
	"\bmetadata\x18\t \x03(\v24.weknora.plugin.datasource.v1.Resource.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb8\x01\n" +
	"\x06Cursor\x12@\n" +
	"\x0elast_sync_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\flastSyncTime\x12B\n" +
	"\x10connector_cursor\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x0fconnectorCursor\x12(\n" +
	"\x10last_schema_hash\x18\x03 \x01(\tR\x0elastSchemaHash\"\x98\x04\n" +
	"\vFetchedItem\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x1b\n" +
	"\tfile_name\x18\x05 \x01(\tR\bfileName\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12S\n" +
	"\bmetadata\x18\b \x03(\v27.weknora.plugin.datasource.v1.FetchedItem.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\t \x01(\bR\tisDeleted\x12,\n" +
	"\x12source_resource_id\x18\n" +
	" \x01(\tR\x10sourceResourceId\x12)\n" +
	"\x10replaces_subtree\x18\v \x01(\bR\x0freplacesSubtree\x12!\n" +
	"\fsubtree_keep\x18\f \x03(\tR\vsubtreeKeep\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x11\n" +
	"\x0fDescribeRequest\"~\n" +
	"\x10DescribeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12\x1c\n" +
	"\tcontracts\x18\x04 \x03(\tR\tcontracts\"O\n" +
	"\x0fValidateRequest\x12<\n" +
	"\x06config\x18\x01 \x01(\v2$.weknora.plugin.datasource.v1.ConfigR\x06config\"<\n" +
	"\x10ValidateResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"q\n" +
	"\x14ListResourcesRequest\x12<\n" +
	"\x06config\x18\x01 \x01(\v2$.weknora.plugin.datasource.v1.ConfigR\x06config\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\"]\n" +
	"\x15ListResourcesResponse\x12D\n" +
	"\tresources\x18\x01 \x03(\v2&.weknora.plugin.datasource.v1.ResourceR\tresources\"z\n" +
	"\x17ResolveAncestorsRequest\x12<\n" +
	"\x06config\x18\x01 \x01(\v2$.weknora.plugin.datasource.v1.ConfigR\x06config\x12!\n" +
	"\fresource_ids\x18\x02 \x03(\tR\vresourceIds\"=\n" +
	"\x18ResolveAncestorsResponse\x12!\n" +
	"\fancestor_ids\x18\x01 \x03(\tR\vancestorIds\"\xb3\x01\n" +
	"\x12FetchStreamRequest\x12<\n" +
	"\x06config\x18\x01 \x01(\v2$.weknora.plugin.datasource.v1.ConfigR\x06config\x12!\n" +
	"\fresource_ids\x18\x02 \x03(\tR\vresourceIds\x12<\n" +
	"\x06cursor\x18\x03 \x01(\v2$.weknora.plugin.datasource.v1.CursorR\x06cursor\"\xf4\x01\n" +
	"\x13FetchStreamResponse\x12?\n" +
	"\x04item\x18\x01 \x01(\v2).weknora.plugin.datasource.v1.FetchedItemH\x00R\x04item\x12F\n" +
	"\n" +
	"checkpoint\x18\x02 \x01(\v2$.weknora.plugin.datasource.v1.CursorH\x00R\n" +
	"checkpoint\x12I\n" +
	"\ffinal_cursor\x18\x03 \x01(\v2$.weknora.plugin.datasource.v1.CursorH\x00R\vfinalCursorB\t\n" +
	"\apayload2\xde\x04\n" +
	"\n" +
	"DataSource\x12i\n" +
	"\bDescribe\x12-.weknora.plugin.datasource.v1.DescribeRequest\x1a..weknora.plugin.datasource.v1.DescribeResponse\x12i\n" +
	"\bValidate\x12-.weknora.plugin.datasource.v1.ValidateRequest\x1a..weknora.plugin.datasource.v1.ValidateResponse\x12x\n" +
	"\rListResources\x122.weknora.plugin.datasource.v1.ListResourcesRequest\x1a3.weknora.plugin.datasource.v1.ListResourcesResponse\x12\x89\x01\n" +
	"\x18ResolveResourceAncestors\x125.weknora.plugin.datasource.v1.ResolveAncestorsRequest\x1a6.weknora.plugin.datasource.v1.ResolveAncestorsResponse\x12t\n" +
	"\vFetchStream\x120.weknora.plugin.datasource.v1.FetchStreamRequest\x1a1.weknora.plugin.datasource.v1.FetchStreamResponse0\x01BKZIgithub.com/Tencent/WeKnora/docreader/proto/plugin/datasource;datasourcev1b\x06proto3"

var (
	file_datasource_proto_rawDescOnce sync.Once
	file_datasource_proto_rawDescData []byte
)

func file_datasource_proto_rawDescGZIP() []byte {
	file_datasource_proto_rawDescOnce.Do(func() {
		file_datasource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datasource_proto_rawDesc), len(file_datasource_proto_rawDesc)))
	})
	return file_datasource_proto_rawDescData
}

var file_datasource_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_datasource_proto_goTypes = []any{
	(*Config)(nil),                   // 0: weknora.plugin.datasource.v1.Config
	(*Resource)(nil),                 // 1: weknora.plugin.datasource.v1.Resource
	(*Cursor)(nil),                   // 2: weknora.plugin.datasource.v1.Cursor
	(*FetchedItem)(nil),              // 3: weknora.plugin.datasource.v1.FetchedItem
	(*DescribeRequest)(nil),          // 4: weknora.plugin.datasource.v1.DescribeRequest
	(*DescribeResponse)(nil),         // 5: weknora.plugin.datasource.v1.DescribeResponse
	(*ValidateRequest)(nil),          // 6: weknora.plugin.datasource.v1.ValidateRequest
	(*ValidateResponse)(nil),         // 7: weknora.plugin.datasource.v1.ValidateResponse
	(*ListResourcesRequest)(nil),     // 8: weknora.plugin.datasource.v1.ListResourcesRequest
	(*ListResourcesResponse)(nil),    // 9: weknora.plugin.datasource.v1.ListResourcesResponse
	(*ResolveAncestorsRequest)(nil),  // 10: weknora.plugin.datasource.v1.ResolveAncestorsRequest
	(*ResolveAncestorsResponse)(nil), // 11: weknora.plugin.datasource.v1.ResolveAncestorsResponse
	(*FetchStreamRequest)(nil),       // 12: weknora.plugin.datasource.v1.FetchStreamRequest
	(*FetchStreamResponse)(nil),      // 13: weknora.plugin.datasource.v1.FetchStreamResponse
	nil,                              // 14: weknora.plugin.datasource.v1.Resource.MetadataEntry
	nil,                              // 15: weknora.plugin.datasource.v1.FetchedItem.MetadataEntry
	(*structpb.Struct)(nil),          // 16: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),    // 17: google.protobuf.Timestamp
}
var file_datasource_proto_depIdxs = []int32{
	16, // 0: weknora.plugin.datasource.v1.Config.credentials:type_name -> google.protobuf.Struct
	16, // 1: weknora.plugin.datasource.v1.Config.settings:type_name -> google.protobuf.Struct
	17, // 2: weknora.plugin.datasource.v1.Resource.modified_at:type_name -> google.protobuf.Timestamp
	14, // 3: weknora.plugin.datasource.v1.Resource.metadata:type_name -> weknora.plugin.datasource.v1.Resource.MetadataEntry
	17, // 4: weknora.plugin.datasource.v1.Cursor.last_sync_time:type_name -> google.protobuf.Timestamp
	16, // 5: weknora.plugin.datasource.v1.Cursor.connector_cursor:type_name -> google.protobuf.Struct
	17, // 6: weknora.plugin.datasource.v1.FetchedItem.updated_at:type_name -> google.protobuf.Timestamp
	15, // 7: weknora.plugin.datasource.v1.FetchedItem.metadata:type_name -> weknora.plugin.datasource.v1.FetchedItem.MetadataEntry
	0,  // 8: weknora.plugin.datasource.v1.ValidateRequest.config:type_name -> weknora.plugin.datasource.v1.Config
	0,  // 9: weknora.plugin.datasource.v1.ListResourcesRequest.config:type_name -> weknora.plugin.datasource.v1.Config
	1,  // 10: weknora.plugin.datasource.v1.ListResourcesResponse.resources:type_name -> weknora.plugin.datasource.v1.Resource
	0,  // 11: weknora.plugin.datasource.v1.ResolveAncestorsRequest.config:type_name -> weknora.plugin.datasource.v1.Config
	0,  // 12: weknora.plugin.datasource.v1.FetchStreamRequest.config:type_name -> weknora.plugin.datasource.v1.Config
	2,  // 13: weknora.plugin.datasource.v1.FetchStreamRequest.cursor:type_name -> weknora.plugin.datasource.v1.Cursor
	3,  // 14: weknora.plugin.datasource.v1.FetchStreamResponse.item:type_name -> weknora.plugin.datasource.v1.FetchedItem
	2,  // 15: weknora.plugin.datasource.v1.FetchStreamResponse.checkpoint:type_name -> weknora.plugin.datasource.v1.Cursor
	2,  // 16: weknora.plugin.datasource.v1.FetchStreamResponse.final_cursor:type_name -> weknora.plugin.datasource.v1.Cursor
	4,  // 17: weknora.plugin.datasource.v1.DataSource.Describe:input_type -> weknora.plugin.datasource.v1.DescribeRequest
	6,  // 18: weknora.plugin.datasource.v1.DataSource.Validate:input_type -> weknora.plugin.datasource.v1.ValidateRequest
	8,  // 19: weknora.plugin.datasource.v1.DataSource.ListResources:input_type -> weknora.plugin.datasource.v1.ListResourcesRequest
	10, // 20: weknora.plugin.datasource.v1.DataSource.ResolveResourceAncestors:input_type -> weknora.plugin.datasource.v1.ResolveAncestorsRequest
	12, // 21: weknora.plugin.datasource.v1.DataSource.FetchStream:input_type -> weknora.plugin.datasource.v1.FetchStreamRequest
	5,  // 22: weknora.plugin.datasource.v1.DataSource.Describe:output_type -> weknora.plugin.datasource.v1.DescribeResponse
	7,  // 23: weknora.plugin.datasource.v1.DataSource.Validate:output_type -> weknora.plugin.datasource.v1.ValidateResponse
	9,  // 24: weknora.plugin.datasource.v1.DataSource.ListResources:output_type -> weknora.plugin.datasource.v1.ListResourcesResponse
	11, // 25: weknora.plugin.datasource.v1.DataSource.ResolveResourceAncestors:output_type -> weknora.plugin.datasource.v1.ResolveAncestorsResponse
	13, // 26: weknora.plugin.datasource.v1.DataSource.FetchStream:output_type -> weknora.plugin.datasource.v1.FetchStreamResponse
	22, // [22:27] is the sub-list for method output_type
	17, // [17:22] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_datasource_proto_init() }
func file_datasource_proto_init() {
	if File_datasource_proto != nil {
		return
	}
	file_datasource_proto_msgTypes[13].OneofWrappers = []any{
		(*FetchStreamResponse_Item)(nil),
		(*FetchStreamResponse_Checkpoint)(nil),
		(*FetchStreamResponse_FinalCursor)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datasource_proto_rawDesc), len(file_datasource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_datasource_proto_goTypes,
		DependencyIndexes: file_datasource_proto_depIdxs,
		MessageInfos:      file_datasource_proto_msgTypes,
	}.Build()
	File_datasource_proto = out.File
	file_datasource_proto_goTypes = nil
	file_datasource_proto_depIdxs = nil
}
